import { useState } from "react";
import { Badge, Button, FileUpload, Modal, StatusIndicator, Tabs } from "../ui";
import { KNOWLEDGE_ASSET_META } from "../../lib/knowledgeAssetMeta";
import { previewSchema, previewValidationSuite } from "../../lib/knowledgeAssetPreview";
import { withMinDuration } from "../../lib/withMinDuration";
import { apiErrorMessage } from "../../api/client";
import { useGenerateAsset, useUploadAsset } from "../../hooks/useKnowledgeAssets";
import type { AssetType, KnowledgeAsset } from "../../api/knowledgeAssets";

interface AssetConfigModalProps {
  agentId: string;
  assetType: AssetType;
  asset: KnowledgeAsset;
  isOpen: boolean;
  onClose: () => void;
}

type Mode = "generate" | "upload";

const GENERATE_EXPLANATION: Record<AssetType, string> = {
  schema: "The agent inspects your connected database's live structure — tables, columns, and relationships.",
  documentation:
    "The agent reads your schema and writes a plain-language explanation of what the data represents.",
  validation_suite:
    "The agent writes realistic business questions to test whether it understands your database correctly.",
};

export function AssetConfigModal({ agentId, assetType, asset, isOpen, onClose }: AssetConfigModalProps) {
  const meta = KNOWLEDGE_ASSET_META[assetType];
  const generateAsset = useGenerateAsset(agentId);
  const uploadAsset = useUploadAsset(agentId);

  const alreadyConfigured = asset.status === "ready";
  const [mode, setMode] = useState<Mode>("generate");
  const [isEditing, setIsEditing] = useState(!alreadyConfigured);
  const [error, setError] = useState<string | null>(null);
  const [isWorking, setIsWorking] = useState(false);

  async function handleGenerate() {
    setError(null);
    setIsWorking(true);
    try {
      const result = await withMinDuration(generateAsset.mutateAsync(assetType), 900);
      if (result.status === "error") {
        setError(result.error_message ?? "Generation failed.");
      } else {
        setIsEditing(false);
      }
    } catch (err) {
      setError(apiErrorMessage(err, "Could not generate this asset."));
    } finally {
      setIsWorking(false);
    }
  }

  async function handleFileSelected(file: File) {
    setError(null);
    setIsWorking(true);
    try {
      await withMinDuration(uploadAsset.mutateAsync({ assetType, file }), 700);
      setIsEditing(false);
    } catch (err) {
      setError(apiErrorMessage(err, "Could not upload that file."));
    } finally {
      setIsWorking(false);
    }
  }

  function renderPreview() {
    if (!asset.content) return null;
    if (assetType === "schema") {
      const preview = previewSchema(asset.content);
      if (!preview) return null;
      return (
        <p className="text-sm text-ink-muted">
          {preview.tableCount} tables detected: {preview.tableNames.join(", ")}
          {preview.tableCount > preview.tableNames.length ? ", …" : ""}
        </p>
      );
    }
    if (assetType === "validation_suite") {
      const preview = previewValidationSuite(asset.content);
      if (!preview) return null;
      return (
        <ul className="list-inside list-disc text-sm text-ink-muted">
          {preview.questions.map((q, i) => (
            <li key={i}>{q}</li>
          ))}
        </ul>
      );
    }
    return (
      <p className="max-h-40 overflow-y-auto whitespace-pre-wrap text-sm text-ink-muted">
        {asset.content.slice(0, 600)}
        {asset.content.length > 600 ? "…" : ""}
      </p>
    );
  }

  return (
    <Modal isOpen={isOpen} onClose={onClose} title={meta.title}>
      <p className="text-sm text-ink-muted">{meta.description}</p>

      {!isEditing && alreadyConfigured && (
        <div className="mt-4 flex flex-col gap-3">
          <div className="flex items-center gap-2">
            <Badge tone="success">Ready</Badge>
            <span className="text-xs text-ink-muted">
              {asset.source === "generated" ? "Generated by the agent" : `Uploaded: ${asset.original_filename}`}
            </span>
          </div>
          <div className="rounded-md border border-border bg-canvas p-3">{renderPreview()}</div>
          <Button variant="secondary" onClick={() => setIsEditing(true)}>
            Replace
          </Button>
        </div>
      )}

      {isEditing && (
        <div className="mt-4 flex flex-col gap-4">
          <Tabs
            items={[
              { value: "generate", label: "Generate automatically" },
              { value: "upload", label: "Upload existing" },
            ]}
            value={mode}
            onChange={(v) => setMode(v as Mode)}
          />

          {mode === "generate" && (
            <div className="flex flex-col gap-3">
              <p className="text-sm text-ink-muted">{GENERATE_EXPLANATION[assetType]}</p>
              <div className="flex items-center gap-3">
                <Button onClick={handleGenerate} isLoading={isWorking}>
                  {isWorking ? "Generating…" : "Generate"}
                </Button>
                {isWorking && <StatusIndicator status="pending" label="Analyzing your data…" />}
              </div>
            </div>
          )}

          {mode === "upload" && (
            <div className="flex flex-col gap-3">
              <FileUpload accept={meta.accept} onFileSelected={handleFileSelected} hint={meta.uploadHint} />
              {isWorking && <StatusIndicator status="pending" label="Uploading and processing…" />}
            </div>
          )}

          {error && (
            <p className="rounded-md border border-danger/20 bg-danger/5 px-3 py-2 text-sm text-danger">{error}</p>
          )}

          {alreadyConfigured && (
            <button
              type="button"
              onClick={() => setIsEditing(false)}
              className="self-start text-sm font-medium text-ink-muted hover:text-ink"
            >
              Cancel
            </button>
          )}
        </div>
      )}
    </Modal>
  );
}
